export const flashcards = [
	{
		slug: 'spanielcina-zaklady',
		name: 'Španielčina základy',
		cards: [
			{ q: 'Hello', a: '¡Hola!' },
			{ q: 'Good morning', a: 'Buenos días' },
			{ q: 'Good day', a: 'Buenos tardes' },
			{ q: 'good night', a: 'Buenos noches' },
			{ q: 'Sir', a: 'Señor' },
			{ q: 'Mrs.', a: 'Señora' },
			{ q: 'Miss', a: 'Señorita' },
			{ q: 'Good bye', a: 'Chao' },
			{ q: 'Bye', a: 'Adiós' },
			{ q: 'See you soon', a: 'Hasta Luego' },
			{ q: 'See you soon', a: 'Hasta pronto' },
			{ q: 'See you tomorrow', a: 'Hasta mañana' },
			{ q: 'Soda', a: 'Una gaseosa' },
			{ q: 'please', a: 'Por favor' },
			{ q: 'Thank you', a: 'Gracias' },
			{ q: "You're welcome", a: 'No hay de qué, De nada, Por nada' },
			{ q: 'Sandwhich', a: 'Un sándwich' },
			{ q: 'Lemonade', a: 'Una limonada' },
			{ q: 'Coffee', a: 'Un café' },
			{ q: 'Pizza', a: 'Una pizza' },
			{ q: 'Taco', a: 'Un taco' },
			{ q: 'Enchilada', a: 'Una enchilada' },
			{ q: 'Tamale', a: 'Un tamal' },
			{ q: 'Monday', a: 'Lunes' },
			{ q: 'Tuesday', a: 'Martes' },
			{ q: 'Wednesday', a: 'Miércoles' },
			{ q: 'Thursday', a: 'Jueves' },
			{ q: 'Friday', a: 'Viernes' },
			{ q: 'Saturday', a: 'Sábado' },
			{ q: 'Sunday', a: 'Domingo' },
			{ q: '1', a: 'Uno' },
			{ q: '2', a: 'Dos' },
			{ q: '3', a: 'Tres' },
			{ q: '4', a: 'Cuatro' },
			{ q: '5', a: 'Cinco' },
			{ q: '6', a: 'Seis' },
			{ q: '7', a: 'Siete' },
			{ q: '8', a: 'Ocho' },
			{ q: '9', a: 'Nueve' },
			{ q: '10', a: 'Diez' },
			{ q: '11', a: 'Once' },
			{ q: '12', a: 'Doce' },
			{ q: '13', a: 'Trece' },
			{ q: '14', a: 'Catorce' },
			{ q: '15', a: 'Quince' },
			{ q: '16', a: 'Dieciséis' },
			{ q: '17', a: 'Diecisiete' },
			{ q: '18', a: 'Dieciocho' },
			{ q: '19', a: 'Diecinueve' },
			{ q: '20', a: 'Veinte' },
			{ q: '21', a: 'Veintiuno' },
			{ q: '22', a: 'Veintidós' },
			{ q: '23', a: 'Veintitrés' },
			{ q: '24', a: 'Veinticuatro' },
			{ q: '25', a: 'Veinticinco' },
			{ q: '26', a: 'Veintiséis' },
			{ q: '27', a: 'Veintisiete' },
			{ q: '28', a: 'Veintiocho' },
			{ q: '29', a: 'Veintinueve' },
			{ q: '30', a: 'Treinta' },
			{ q: 'Spring', a: 'La primavera' },
			{ q: 'Summer', a: 'El verano' },
			{ q: 'Winter', a: 'El invierno' },
			{ q: 'Autumn', a: 'El otoño' },
			{ q: 'Boy', a: 'El muchacho' },
			{ q: 'Girl', a: 'La muchacha' },
			{ q: 'Friend', a: 'Amigo/a' },
			{ q: 'Student', a: 'Alumno/a' },
			{ q: 'School', a: 'Escuela/Colegio' },
			{ q: 'Tall', a: 'Alto/a' },
			{ q: 'Short', a: 'Bajo/a' },
			{ q: 'Handsome/pretty', a: 'Guapo/bonita' },
			{ q: 'Ugly', a: 'Feo/a' },
			{ q: 'Blonde hair', a: 'Rubio/a' },
			{ q: 'Dark hair', a: 'Moreno/a' },
			{ q: 'Red hair', a: 'Pelirrojo/a' },
			{ q: 'Funny', a: 'Gracioso/a, Cómico/a' },
			{ q: 'Serious', a: 'Serio/a' },
			{ q: 'Hard working', a: 'Ambicioso/a' },
			{ q: 'Lazy', a: 'Perezoso/a' },
			{ q: 'Very, much', a: 'Muy' },
			{ q: 'I am', a: '(Yo) Soy' },
			{ q: 'You are', a: 'Tú eres' },
			{ q: 'He is', a: 'él es' },
			{ q: 'She is', a: 'ella es' },
			{ q: 'No', a: 'No' },
			{ q: 'Skinny', a: 'Flaco/a' },
			{ q: 'Fat', a: 'Gordo/a' },
			{ q: 'happy', a: 'Gracioso/a' },
			{ q: 'Good', a: 'Bueno/a' },
			{ q: 'Fantastic', a: 'Fantástico/a' },
			{ q: 'Timid', a: 'Tímido/a' },
			{ q: 'Sincere', a: 'Sincero/a' },
			{ q: 'Honest', a: 'Honesto/a' },
			{ q: 'Generous', a: 'Generoso/a' },
			{ q: 'Nice', a: 'Simpático/a' },
			{ q: 'Students', a: 'Los Alumnos' },
			{ q: 'Small', a: 'Pequeña' },
			{ q: 'Difficult', a: 'Difícil' },
			{ q: 'Easy', a: 'Fácil' },
			{ q: 'Big', a: 'Grande' },
			{ q: 'Lots/Many', a: 'Muchos' },
			{ q: 'Interesting', a: 'Interesante' },
			{ q: 'Course', a: 'El curso' },
			{ q: 'The class', a: 'La clase' },
			{ q: 'The teacher', a: 'El profesor, la profesora' },
			{ q: 'Intelligent', a: 'Inteligente' },
			{ q: 'Popular', a: 'Popular' },
			{ q: 'Sciences', a: 'Las ciencias' },
			{ q: 'Biology', a: 'La biología' },
			{ q: 'Chemistry', a: 'La química' },
			{ q: 'Physics', a: 'La física' },
			{ q: 'Math', a: 'Las Matemáticas' },
			{ q: 'Arithmetic', a: 'La aritmética' },
			{ q: 'Algebra', a: 'El álgebra' },
			{ q: 'Geometry', a: 'La geometría' },
			{ q: 'Calculus', a: 'El cálculo' },
			{ q: 'Languages', a: 'Las lenguas' },
			{ q: 'Spanish', a: 'El español' },
			{ q: 'English', a: 'El inglés' },
			{ q: 'French', a: 'El Francés' },
			{ q: 'German', a: 'El alemán' },
			{ q: 'Latin', a: 'El latín' },
			{ q: 'Social Studies', a: 'Las Ciencias Sociales' },
			{ q: 'History', a: 'La historia' },
			{ q: 'Geography', a: 'la geografía' },
			{ q: 'Other subjects and disciplines', a: 'Otras Asignaturas o disciplinas' },
			{ q: 'Physical Education', a: 'La educación física' },
			{ q: 'Music', a: 'La música' },
			{ q: 'Art', a: 'El arte' },
			{ q: 'Home economics', a: 'La economía doméstica' },
			{ q: 'Computer Science', a: 'La informática' },
			{ q: '31', a: 'Treinta y uno' },
			{ q: '32', a: 'Treinta y dos' },
			{ q: '33', a: 'Treinta y tres' },
			{ q: '34', a: 'Treinta y cuatro' },
			{ q: '35', a: 'Treinta y cinco' },
			{ q: '36', a: 'Treinta y seis' },
			{ q: '37', a: 'Treinta y siete' },
			{ q: '38', a: 'Treinta y ocho' },
			{ q: '39', a: 'Treinta y nueve' },
			{ q: '40', a: 'Cuarenta' },
			{ q: '50', a: 'Cuncuenta' },
			{ q: '60', a: 'Sesenta' },
			{ q: '70', a: 'Setenta' },
			{ q: '80', a: 'Ochenta' },
			{ q: '90', a: 'Noventa' },
			{ q: 'We are', a: 'Nosotros(as) Somos' },
			{ q: 'They are (men)', a: 'Ellos son' },
			{ q: 'They are (women)', a: 'Ellas son' },
			{ q: 'You all are', a: 'Ustedes son' },
			{ q: 'Noon', a: 'Es el mediodía' },
			{ q: 'Midnight', a: 'Es la medianoche' },
			{ q: 'Notebook', a: 'Un cuaderno/ un bloc' },
			{ q: 'Bookbag', a: 'La mochila' },
			{ q: 'Folder', a: 'Una Carpeta' },
			{ q: 'Workbook', a: 'Un libro' },
			{ q: 'Calculator', a: 'Una Calculadora' },
			{ q: 'Marker', a: 'Un marcador' },
			{ q: 'Pen', a: 'Un bolígrafo/ una pluma' },
			{ q: 'Disk', a: 'Un disquete' },
			{ q: 'Eraser', a: 'Una goma de borrar' },
			{ q: 'Pencil, two pencils', a: 'Un lápiz, dos lápices' },
			{ q: 'Piece of paper', a: 'Una hoja de papel' },
			{ q: 'Look for', a: 'Busca' },
			{ q: 'Look at', a: 'Mira' },
			{ q: 'Needs', a: 'Necesita' },
			{ q: 'School supplies', a: 'Materiales escolares' },
			{ q: 'Employee', a: 'Dependiente,a' },
			{ q: 'Employee', a: 'Empleae,a' },
			{ q: 'I, he, she, to, they, we talk', a: 'Hablo,a,as,ar,an,amos' },
			{ q: 'Pay', a: 'Paga' },
			{ q: 'Cash register', a: 'Caja' },
			{ q: 'Pay at the cash register', a: 'Paga in la caja' },
			{ q: 'Carry, wear', a: 'lleva' },
			{ q: 'Clothing store', a: 'Ropa' },
			{ q: 'Stationary store', a: 'Una papeleria' },
			{ q: 'Shorts', a: 'Un pantalón corto' },
			{ q: 'Pants', a: 'Un pantalón largo' },
			{ q: 'Blue jean', a: 'Un blue jean' },
			{ q: 'Socks', a: 'Los calcetines' },
			{ q: 'Pair of tennis shoes', a: 'Un par de tenis' },
			{ q: 'Tie', a: 'Una corbata' },
			{ q: 'Shirt', a: 'Una camisa' },
			{ q: 'T-shirt, undershirt', a: 'La camiseta, un t-shirt' },
			{ q: 'Jacket', a: 'Una chaqueta' },
			{ q: 'Size (Shoes)', a: 'El número' },
			{ q: 'Size (Shirt)', a: 'La talla/El tamaño' },
			{ q: 'Shoes', a: 'Los zapatos' },
			{ q: 'Skirt', a: 'Una falda' },
			{ q: 'Hat', a: 'Una gorra' },
			{ q: 'Blouse', a: 'Una blusa' },
			{ q: 'Suit', a: 'Un Traje' },
			{ q: 'Blue', a: 'Azul' },
			{ q: 'Red', a: 'Rojo/a' },
			{ q: 'Black', a: 'Negro/a' },
			{ q: 'Yellow', a: 'Amarillo/a' },
			{ q: 'White', a: 'Blanco/a' },
			{ q: 'Pink', a: 'Rosado/a' },
			{ q: 'Orange', a: 'Anaranjado/a' },
			{ q: 'Green', a: 'Verde' },
			{ q: 'Brown', a: 'De color marrón' },
			{ q: 'Gray', a: 'Gris' },
			{ q: '100', a: 'Ciento, Cien' },
			{ q: '200', a: 'Doscientos' },
			{ q: '300', a: 'Trescientos' },
			{ q: '400', a: 'Cuatrocientos' },
			{ q: '500', a: 'Quientos' },
			{ q: '600', a: 'Seiscientos' },
			{ q: '700', a: 'Setecientos' },
			{ q: '800', a: 'Ochocientos' },
			{ q: '900', a: 'Novecientos' },
			{ q: '1000', a: 'Mil' },
			{ q: '150', a: 'Ciento Cincuenta' },
			{ q: '790', a: 'Setecientos Noventa' },
			{ q: '1800', a: 'Mil ochocientos' },
			{ q: 'By foot', a: 'A pie' },
			{ q: 'By car', a: 'En carro, en coche' },
			{ q: 'By school bus', a: 'En el bus escolar' },
			{ q: 'S/he teaches', a: 'Enseña' },
			{ q: 'They take', a: 'Toman' },
			{ q: 'They go', a: 'Van' },
			{ q: 'They arrive', a: 'Llegan' },
			{ q: 'They enter', a: 'Entran' },
			{ q: 'They are', a: 'Están' },
			{ q: 'The classroom', a: 'La sala de clase' },
			{ q: 'Others', a: 'Otros' },
			{ q: 'Some', a: 'Algunos' },
			{ q: 'About/around (Time)', a: 'A eso de' },
			{ q: 'Test', a: 'Un examen' },
			{ q: 'A good/high grade', a: 'Una nota buena/ una nota alta' },
			{ q: 'A bad/low grade', a: 'Una nota mala/ una nota baja' },
			{ q: 'Chalkboard', a: 'El pizarrón/ la pizarra' },
			{ q: 'Lesson', a: 'Lección' },
			{ q: 'Explain', a: 'Explica' },
			{ q: 'Pay attention', a: 'Prestan Atención' },
			{ q: 'Take notes', a: 'Toman apuntes' },
			{ q: 'To listen', a: 'Eschuchar' },
			{ q: 'A party', a: 'La fiesta' },
			{ q: 'A snack', a: 'Una merienda' },
			{ q: 'To dance', a: 'Bailar' },
			{ q: 'To sing', a: 'Cantar' },
			{ q: 'Video', a: 'Un video' },
			{ q: 'DVD', a: 'Un DVD' },
			{ q: 'CD', a: 'Un CD' },
			{ q: 'But', a: 'Pero' },
			{ q: '2000', a: 'Dos mil' },
			{ q: '2002', a: 'Dos mil dos' },
			{ q: '2500', a: 'Dos mil quinientos' },
			{ q: '3000', a: 'Tres mil' },
			{ q: '3015', a: 'Tres mil quince' },
			{ q: '3650', a: 'Tres mil seisciento cincuenta' },
			{ q: '1200', a: 'Mil doscientos' },
			{ q: '1492', a: 'Mil cuatrocientos noventa y dos' },
			{ q: '1814', a: 'Mil ochocientos catorce' },
			{ q: '1898', a: 'Mil ochocientos noventa y ocho' },
			{ q: '1,000,000', a: 'Un millón' },
			{ q: '2,000,000', a: 'Dos millones' },
			{ q: 'January', a: 'Enero' },
			{ q: 'February', a: 'Febrero' },
			{ q: 'March', a: 'Marzo' },
			{ q: 'April', a: 'Abril' },
			{ q: 'May', a: 'Mayo' },
			{ q: 'June', a: 'Junio' },
			{ q: 'July', a: 'Julio' },
			{ q: 'August', a: 'Agosto' },
			{ q: 'September', a: 'Septiembre' },
			{ q: 'October', a: 'Octubre' },
			{ q: 'November', a: 'Noviembre' },
			{ q: 'December', a: 'Diciembre' },
			{ q: 'Order (Restaurant)', a: 'La orden' },
			{ q: 'To read', a: 'Leer' },
			{ q: 'Table', a: 'La mesa' },
			{ q: 'Bill/check', a: 'La cuenta' },
			{ q: 'To eat', a: 'Comer' },
			{ q: 'Waiter/waitress', a: 'El/la mesero(a), el/la camarero(a)' },
			{ q: 'Free', a: 'Libre' },
			{ q: 'To drink', a: 'Beber' },
			{ q: 'Occupied/taken', a: 'Ocupado/a' },
			{ q: 'May I help you?', a: '¿Qué desean ustedes?' },
			{ q: 'Menu', a: 'El menú' },
			{ q: 'To see/ to watch', a: 'Ver' },
			{ q: 'Is the tip included?', a: '¿Está incluido el servicio?' },
			{ q: 'Drinks, beverages', a: 'Los refrescos' },
			{ q: 'Yogurt', a: 'Un yogur' },
			{ q: 'Tortilla', a: 'Una tortilla' },
			{ q: 'Soup', a: 'Una sopa' },
			{ q: 'Salad', a: 'Una ensalada' },
			{ q: 'Black coffee/ coffee with milk', a: 'Un café solo, con leche' },
			{ q: 'Dessert', a: 'El postre' },
			{ q: 'Cafe', a: 'El café' },
			{ q: 'Iced tea', a: 'Un té helado' },
			{ q: 'Ham', a: 'El jamón' },
			{ q: 'Vanilla ice cream, chocolate ice cream', a: 'Un helado de vainilla, de chocolate' },
			{ q: 'Cheese', a: 'El queso' },
			{ q: 'Cereal', a: 'El cereal' },
			{ q: 'Hamburger', a: 'Una hamburguesa' },
			{ q: 'Sweet roll', a: 'Un pan dulce' },
			{ q: 'Toast', a: 'El pan tostado' },
			{ q: 'French fries', a: 'Papas fritas' },
			{ q: 'Market', a: 'El mercado' },
			{ q: 'Super market', a: 'El super mercado' },
			{ q: 'Bag', a: 'Una bolsa' },
			{ q: 'Kilogram', a: 'Un kilo' },
			{ q: 'How much is (are) _____?', a: '¿A cuánto está(n)?' },
			{ q: 'Anything else', a: 'Algo más' },
			{ q: 'Nothing else', a: 'Nada más' },
			{ q: 'Can', a: 'Un bote, una lata' },
			{ q: 'Frozen food', a: 'Congelado(a)' },
			{ q: 'Package', a: 'Un paquete' },
			{ q: 'To sell', a: 'Vender' },
			{ q: 'Vegetables', a: 'Los vegetales' },
			{ q: 'Peas', a: 'Los guisantes' },
			{ q: 'Beans', a: 'Las habichuelas, los frijoles' },
			{ q: 'Green beans', a: 'Las judías verdes' },
			{ q: 'Carrots', a: 'Las zanahorias' },
			{ q: 'Potatoes', a: 'Las papas' },
			{ q: 'Lettuce', a: 'La lechuga' },
			{ q: 'Fruit', a: 'Las frutas' },
			{ q: 'Oranges', a: 'Las naranjas' },
			{ q: 'Apples', a: 'Las manzanas' },
			{ q: 'Bananas', a: 'Los plátanos' },
			{ q: 'Tomatoes', a: 'Los tomates' },
			{ q: 'Meat', a: 'La carne' },
			{ q: 'Steak', a: 'El biftec' },
			{ q: 'Shellfish', a: 'Los mariscos' },
			{ q: 'Fish', a: 'El pescado' },
			{ q: 'Chicken', a: 'El pollo' },
			{ q: 'Egg', a: 'El huevo' },
			{ q: 'Tuna', a: 'El atún' },
			{ q: 'Rice', a: 'El arroz' },
			{ q: 'Food/meal', a: 'Las comidas' },
			{ q: 'Breakfast', a: 'El desayuno' },
			{ q: 'Lunch', a: 'El almuerzo' },
			{ q: 'Dinner', a: 'La cena' },
			{ q: 'Family', a: 'La familia' },
			{ q: 'Relatives', a: 'Los parientes' },
			{ q: 'Father', a: 'El padre' },
			{ q: 'Mother', a: 'La madre' },
			{ q: 'Husband', a: 'El esposo, el marido' },
			{ q: 'Wife', a: 'La esposa, la mujer' },
			{ q: 'Son/daughter', a: 'El/la hijo(a)' },
			{ q: 'Brother/sister', a: 'El/la hermano(a)' },
			{ q: 'Grandfather/grandmother', a: 'El/la abuelo(a)' },
			{ q: 'Grandson/granddaughter', a: 'El/la nieto(a)' },
			{ q: 'Uncle/aunt', a: 'El/la tío(a)' },
			{ q: 'Nephew/niece', a: 'El/la sobrino(a)' },
			{ q: 'Cousin', a: 'El/la primo(a)' },
			{ q: 'Cat', a: 'El/la gato(a)' },
			{ q: 'Dog', a: 'El/la perro(a)' },
			{ q: 'Prepare', a: 'Preparar' },
			{ q: 'To', a: 'A' },
			{ q: 'In', a: 'En' },
			{ q: 'At', a: 'A' },
			{ q: 'As', a: 'Como' },
			{ q: 'Hey', a: 'Oye' },
			{ q: 'Sometimes', a: 'Veces' },
			{ q: 'After', a: 'Después' },
			{ q: 'House', a: 'Casa' }
		]
	},
	{
		slug: 'mvp-mezinarodni-smouvy',
		name: 'MVP Mezinárodní smlouvy',
		cards: [
			{
				q: 'Co je definice mezinárodní smlouvy podle VÚSP z roku 1969?',
				a: 'Mezinárodní dohoda uzavřená mezi státy písemnou formou, řídící se mezinárodním právem, sepsaná v jediné nebo ve dvou či více souvisících listinách, ať je její název jakýkoliv.'
			},
			{
				q: 'Jaké jsou tři hlavní typy mezinárodních smluv podle subjektů?',
				a: 'Dvoustranné, vícestranné, mnohostranné.'
			},
			{
				q: 'Co znamená zásada "pacta sunt servanda"?',
				a: 'Každá platná smlouva zavazuje smluvní strany a musí být jimi plněna v dobré víře.'
			},
			{
				q: 'Kde ve Vídeňské úmluvě o smluvním právu je upraveno pravidlo "pacta sunt servanda"?',
				a: 'Článek 26.'
			},
			{
				q: 'Jaké jsou formy zavázání se mezinárodní smlouvou?',
				a: 'Podpis, ratifikace, přijetí, přistoupení.'
			},
			{
				q: 'Co je potřeba pro ratifikaci prezidentské smlouvy podle Ústavy ČR?',
				a: 'Souhlas obou komor Parlamentu.'
			},
			{
				q: 'Co je to výhrada k mezinárodní smlouvě?',
				a: 'Jednostranné prohlášení, jímž stát zamýšlí vyloučit nebo změnit právní účinek určitých ustanovení smlouvy při jejich použití vůči tomuto státu.'
			},
			{
				q: 'Jaké jsou důvody relativní neplatnosti mezinárodní smlouvy?',
				a: 'Omyl, podvod, podplacení zástupce státu, porušení vnitrostátního práva, omezení plné moci.'
			},
			{
				q: 'Jaké je základní pravidlo výkladu mezinárodní smlouvy podle VÚSP?',
				a: 'Smlouva musí být vykládána v dobré víře, v souladu s obvyklým významem výrazů ve smlouvě v jejich celkové souvislosti, s přihlédnutím k předmětu a účelu smlouvy.'
			},
			{
				q: 'Co je podstatná změna okolností (rebus sic stantibus) jako důvod k ukončení smlouvy?',
				a: 'Změna okolností, které existovaly v době uzavření smlouvy, musí být podstatná, nepředvídaná a zásadně mění realizovatelnost závazků.'
			},
			{
				q: 'Jaké jsou způsoby ukončení platnosti mezinárodní smlouvy?',
				a: 'Uplynutí času, splnění smlouvy, rozvazovací podmínka, dohoda stran, výpověď, nemožnost plnění, podstatná změna okolností, podstatné porušení smlouvy.'
			},
			{
				q: 'Co je to tacitní smlouva?',
				a: 'Smlouva, kde se konsensus vytváří konkludentním chováním stran a ne jen tichým souhlasem.'
			},
			{
				q: 'Jaké jsou základní náležitosti pro vznik mezinárodní smlouvy?',
				a: 'Způsobilý předmět, způsobilé strany, způsobilí zástupci smluvních stran, řádný projev vůle.'
			},
			{
				q: 'Co je to prezidentská smlouva podle Ústavy ČR?',
				a: 'Smlouva, jejíž ratifikace vyžaduje souhlas obou komor Parlamentu.'
			},
			{
				q: 'Kdy je možné uplatnit argument nemožnosti plnění smlouvy?',
				a: 'Když předmět nezbytný pro plnění smlouvy definitivně zmizí nebo je zničen.'
			},
			{ q: 'Co znamená "erga omnes" v kontextu mezinárodního práva?', a: 'Účinky vůči všem.' },
			{
				q: 'Jaké jsou důvody absolutní neplatnosti mezinárodní smlouvy?',
				a: 'Porušení kogentní normy mezinárodního práva, vynucení souhlasu státem použitím síly.'
			},
			{
				q: 'Co je to výkladová dohoda?',
				a: 'Dohoda mezi stranami smlouvy o výkladu jejích ustanovení.'
			},
			{
				q: 'Jaké jsou důsledky podstatného porušení mezinárodní smlouvy?',
				a: 'Poškozená strana může ukončit platnost smlouvy nebo ji suspendovat.'
			},
			{
				q: 'Co je to Výbor pro lidská práva?',
				a: 'Orgán OSN monitorující dodržování Mezinárodního paktu o občanských a politických právech.'
			},
			{
				q: 'Jaký je právní význam nečinnosti v mezinárodním právu?',
				a: 'Může být považována za souhlas nebo uznání stavu.'
			},
			{
				q: 'Jaký význam má pravidlo "pacta sunt servanda" pro daný spor?',
				a: 'Závaznost plnění smluvních závazků v dobré víře.'
			},
			{
				q: 'Jaký je proces sjednávání mezinárodních smluv v rámci EU?',
				a: 'Sjednávání, vnitrostátní projednávání, provádění a ukončování platnosti.'
			},
			{
				q: 'Co je to depozitář mezinárodní smlouvy?',
				a: 'Orgán, u kterého jsou uloženy originály smlouvy.'
			},
			{
				q: 'Kdy může stát napadnout právní závaznost mezinárodní smlouvy?',
				a: 'V případě nesouladu se svou vnitrostátní právní úpravou.'
			},
			{ q: 'Co je příklad politického typu mezinárodní smlouvy?', a: 'Mírová smlouva.' },
			{
				q: 'Jaký je rozdíl mezi výhradou a stálým odpůrcem v mezinárodním právu?',
				a: 'Výhrada se týká smluvního práva, stálý odpůrce odmítá vznik obyčeje.'
			},
			{
				q: 'Co znamená "ius cogens"?',
				a: 'Kogentní norma, závazná pravidla, od kterých není dovoleno odchýlit se.'
			},
			{
				q: 'Jaký je význam případu Gabčíkovo-Nagymaros?',
				a: 'Řešení sporů týkajících se následné nemožnosti plnění a podstatné změny okolností.'
			},
			{
				q: 'Jaké jsou typy zástupců smluvních stran způsobilých pro uzavírání smluv?',
				a: 'Hlava státu, předseda vlády, ministr zahraničních věcí, vedoucí diplomatické mise.'
			},
			{
				q: 'Jaká je role generálního tajemníka OSN při mezinárodních smlouvách?',
				a: 'Přijímá a rozesílá texty výhrad.'
			},
			{
				q: 'Co je to soft-law v kontextu mezinárodního práva?',
				a: 'Právně nezávazné politické nástroje, např. závěrečný helsinský akt 1975.'
			},
			{
				q: 'Jaký je postup při přistoupení ke stávající mezinárodní smlouvě?',
				a: 'Přijetí obsahu smlouvy bez možnosti jej ovlivnit.'
			},
			{
				q: 'Jaký je účel článku 102 Charty OSN?',
				a: 'Registrace smluv u OSN pro jejich účinnost před orgány OSN.'
			},
			{
				q: 'Co znamená "bona fide" ve vztahu k plnění mezinárodní smlouvy?',
				a: 'Plnění v dobré víře, bez maření předmětu a smyslu smlouvy.'
			},
			{
				q: 'Jaký je význam případu Chrámu Preah Vihear?',
				a: 'Vymezení hranic států a právní význam nečinnosti.'
			},
			{
				q: 'Jaké jsou formy mezinárodních smluv podle počtu smluvních stran?',
				a: 'Dvoustranné, vícestranné, mnohostranné.'
			},
			{
				q: 'Co je to ratifikace mezinárodní smlouvy?',
				a: 'Proces schválení smlouvy vnitrostátními orgány a následné formální uznání na mezinárodní úrovni.'
			},
			{
				q: 'Jaké jsou důsledky rozporu smlouvy s nově vzniklým kogentním pravidlem?',
				a: 'Neplatnost smlouvy ex nunc.'
			},
			{
				q: 'Jaké jsou základní prvky každé mezinárodní smlouvy?',
				a: 'Konsensus, souhlasný projev vůle stran být smlouvou vázán.'
			},
			{
				q: 'Co je vnitrostátní fáze ratifikace?',
				a: 'Schválení smlouvy parlamentem a podpis hlavy státu.'
			},
			{
				q: 'Jaký je význam článku 18 VÚSP?',
				a: 'Povinnost státu zdržet se jednání mařícího předmět a účel smlouvy před jejím vstupem v platnost.'
			},
			{
				q: 'Co je hlavní funkcí sbírky mezinárodních smluv podle českého práva?',
				a: 'Publikace platných mezinárodních smluv, jimiž je Česká republika vázána.'
			},
			{
				q: 'Jaké jsou doplňkové prostředky výkladu mezinárodní smlouvy?',
				a: 'Travaux préparatoires, následná praxe, okolnosti uzavření.'
			}
		]
	}
];
